version: '3.5'
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      target: nginx
    image: nginx
    container_name: mynginx
    restart: always
    depends_on:
      - db
      - wordpress
    volumes:
      - nginx_v:/var/www/
    ports:
      - 443:443
    hostname: dbredykh.42.fr
    networks:
      - webnet

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      target: wordpress
    image: wordpress
    container_name: mywordpress
    restart: always
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - nginx_v:/var/www/
    networks:
      - webnet

  db:
    image: mariadb
    container_name: mymariadb
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_v:/var/lib/mysql
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db_v:
    driver: local
    driver_opts:
      type: none
      device: /home/dbredykh/data/maria
      o: bind
  nginx_v:
    driver: local
    driver_opts:
      type: none
      device: /home/dbredykh/data/nginx
      o: bind
