services:
  nginx:
    build: ./requirements/nginx
    container_name: mynginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - nginx_v:/var/www/
    ports:
      - 443:443
    hostname: dbredykh.42.fr
    networks:
      - webnet

  wordpress:
    build: ./requirements/wordpress
    container_name: mywordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - nginx_v:/var/www/
    networks:
      - webnet
    env_file:
      - .env


  mariadb:
    build: ./requirements/mariadb
    container_name: mymariadb
    restart: always
    volumes:
      - db_v:/var/lib/mysql
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db_v:
    driver: local
    driver_opts:
      type: none
      device: /home/dbredykh/data/maria
      o: bind
  nginx_v:
    driver: local
    driver_opts:
      type: none
      device: /home/dbredykh/data/nginx
      o: bind
